Repository SuperOfficeDocs/docs-next, pull requests merged in 2025-07, with the labels that each got.

#160 cicd: removed temporary fixes added to github actions deployment
  .github/workflows/deploy.yml
  src/content.config.ts
Labels: 🔧 CI/CD

#157 feat: restyle directives using remark plugin
  astro.config.mjs
  remark-directive-note.mjs
  src/plugins/RestyleDirectives.js
  src/styles/main.css
Labels: 📌 MVP, 🆕 new

#164 cicd: update build workflow and content collections to get external content
  .github/workflows/deploy.yml
  package.json
  src/content.config.ts
  src/pages/de/[...slug].astro
  src/pages/en/[...slug].astro
  src/pages/en/api/reference/webapi/[...slug].astro
  src/pages/release-notes/[...slug].astro
Labels: 🔧 CI/CD

#165 feat: update frontmatter terms and refactor content schema
  src/content.config.ts
  src/content.schema.ts
  src/pages/contribute/[...slug].astro
  src/pages/contribute/[subcategory].astro
  src/pages/en/api/reference/webapi/[...slug].astro
  src/pages/release-notes/[...slug].astro
  src/utils/getTableOfContentsFromCollection.ts
Labels: ✏️ content

#167 feat: include markdown files from api folder
  src/content.config.ts
Labels: 📌 MVP, 🔧 CI/CD

#169 fix: updated and renamed stripFilePathAndExtension
  src/pages/contribute/[...slug].astro
  src/pages/de/[...slug].astro
  src/pages/en/[...slug].astro
  src/pages/en/api/reference/webapi/[...slug].astro
  src/pages/release-notes/[...slug].astro
  src/utils/slugUtils.ts
Labels: 🐜 bug

#171 chore: added toc fies from api/reference
  src/content/docs/en/api/reference/netserver/core/toc.yml
  src/content/docs/en/api/reference/netserver/services/toc.yml
  src/content/docs/en/api/reference/netserver/toc.yml
  src/content/docs/en/api/reference/restful/agent/toc.yml
  src/content/docs/en/api/reference/restful/rest/toc.yml
  src/content/docs/en/api/reference/restful/toc.yml
  src/content/docs/en/api/reference/web/toc.yml
Labels: ✏️ content

#177 feat: added cross-env package to set env
  package-lock.json
  package.json
Labels: 🔧 CI/CD

#181 #162 enable astro redirect from integration
  astro.config.mjs
  package-lock.json
  package.json
  src/pages/de/[...slug].astro
  src/pages/en/[...slug].astro
  src/pages/release-notes/[...slug].astro
  src/utils/slugUtils.ts
Labels: 🔧 CI/CD, dependencies

#183 fix: updated contribution collection import pattern
  src/content.config.ts
Labels: 🐜 bug

#185 #184 Conditionally exclude static landing page in config
  astro.config.mjs
Labels: 🐜 bug

#193 style: changed styling in search bar and fixed header responsiveness
  src/components/Header.astro
  src/navigation.js
  src/styles/main.css
Labels: 🔎 search, 📱 responsiveness

#196 #195 Add MarkdownPage wrapper component
  src/components/MarkdownPage.astro
  src/pages/contribute/[...slug].astro
  src/pages/de/[...slug].astro
  src/pages/en/[...slug].astro
  src/pages/en/database/[...slug].astro
  src/pages/en/developer-portal/[...slug].astro
  src/pages/release-notes/[...slug].astro
  src/utils/tocUtils.ts
Labels: ✏️ content

#199 #190 Segment route and rendering of automation, service, and ui
  src/pages/en/[...slug].astro
  src/pages/en/automation/[...slug].astro
  src/pages/en/service/[...slug].astro
  src/pages/en/ui/[...slug].astro
Labels: 🔧 performance

#201 #200 Isolate en/learn
  src/pages/contribute/index.astro
  src/pages/en/[...slug].astro
  src/pages/en/api/reference/webapi/[...slug].astro
  src/pages/en/learn/[...slug].astro
  src/utils/contentUtils.ts
  src/utils/getTableOfContentsFromCollection.ts
  src/utils/tocUtils.ts
Labels: 🔧 performance

#203 #202 Rewrite category and subcategory routes
  src/pages/de/[...subcategory].astro
  src/pages/en/[...category].astro
  src/pages/en/[...subcategory].astro
  src/pages/en/[category].astro
  src/pages/en/[subcategory].astro
  src/utils/getYamlContent.ts
  src/utils/slugUtils.ts
Labels: 🔧 performance

#204 #182 add all languages
  src/content.config.ts
  src/pages/da/[...slug].astro
  src/pages/da/[...subcategory].astro
  src/pages/da/[category].astro
  src/pages/nl/[...slug].astro
  src/pages/nl/[...subcategory].astro
  src/pages/nl/[category].astro
  src/pages/no/[...slug].astro
  src/pages/no/[...subcategory].astro
  src/pages/no/[category].astro
  src/pages/sv/[...slug].astro
  src/pages/sv/[...subcategory].astro
  src/pages/sv/[category].astro
Labels: 📌 MVP, ✏️ content

#210 #206 refactor reference docs and webapi
  src/components/WebApiClass.astro
  src/components/WebApiPage.astro
  src/content.config.ts
  src/pages/en/api/reference/[...slug].astro
  src/pages/en/api/reference/webapi/[...slug].astro
  src/utils/slugUtils.ts
Labels: 🔧 performance

#213 #211 Add netserver-scripting reference
  src/content.config.ts
  src/pages/en/automation/netserver-scripting/[...slug].astro
Labels: 📌 MVP, ✏️ content

#214 #212 Loosen exclude pattern for automation
  src/content.config.ts
Labels: ✏️ content

#218 #215 Initial YamlManagedReference handling for CRMScript
  src/components/Link.astro
  src/components/YamlCodeBlock.astro
  src/components/YamlExampleBlock.astro
  src/components/YamlManagedReferenceClass.astro
  src/components/YamlManagedReferenceConstructor.astro
  src/components/YamlManagedReferenceContent.astro
  src/components/YamlManagedReferenceEnum.astro
  src/components/YamlManagedReferenceMethod.astro
  src/components/YamlManagedReferenceNamespace.astro
  src/content.config.ts
  src/content.schema.ts
  src/layouts/YamlManagedReference.astro
  src/pages/en/automation/crmscript/[...slug].astro
  src/types/YamlManagedReferenceTypes.ts
  src/utils/yamlManagedReferenceUtils.ts
Labels: ✏️ content, 🎨 styling

#233 style: minor header styling changes
  src/components/Header.astro
Labels: 🎨 styling

#235 fix: updated baseUrl of links in footer, move data source fils
  e2e-tests/tests/index.spec.ts
  src/components/Audience.astro
  src/components/Hero.astro
  src/components/QuickAccessShortcuts.astro
  src/data/audience.ts
  src/data/navigation.ts
  src/layouts/Base.astro
  src/pages/index.astro
Labels: 🐜 bug
